# Generated by Django 5.0.6 on 2026-07-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='planificada', max_length=20)),
                ('distancia_total_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tiempo_estimado_min', models.IntegerField(blank=True, null=True)),
                ('geometria_ruta', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rutas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RutaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_parada', models.SmallIntegerField()),
                ('hora_estimada', models.DateTimeField(blank=True, null=True)),
                ('hora_real', models.DateTimeField(blank=True, null=True)),
                ('estado_parada', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
            ],
            options={
                'db_table': 'ruta_pedidos',
                'ordering': ['orden_parada'],
            },
        ),
    ]
