# Generated by Django 5.0.6 on 2026-07-17 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0002_initial'),
        ('rutas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='repartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rutapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='rutapedido',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='rutas.ruta'),
        ),
        migrations.AlterUniqueTogether(
            name='rutapedido',
            unique_together={('ruta', 'pedido')},
        ),
    ]
