# Generated by Django 5.0.6 on 2026-07-17 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='repartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialestadopedido',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.estadopedido'),
        ),
        migrations.AddField(
            model_name='historialestadopedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_destino', to='usuarios.direccion'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_origen', to='usuarios.direccion'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.estadopedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_repartidor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialestadopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='pedidos.pedido'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente'], name='pedidos_cliente_e28e20_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['repartidor'], name='pedidos_reparti_99a976_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='pedidos_estado__419f92_idx'),
        ),
        migrations.AddIndex(
            model_name='historialestadopedido',
            index=models.Index(fields=['pedido'], name='historial_e_pedido__859575_idx'),
        ),
    ]
