# Generated by Django 5.0.6 on 2026-08-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_seed_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ruta_distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ruta_duracion_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ruta_geometria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
