# Generated by Django 5.0.6 on 2026-07-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RendimientoRepartidor',
            fields=[
                ('repartidor_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('repartidor', models.CharField(max_length=201)),
                ('total_entregas', models.IntegerField()),
                ('entregas_a_tiempo', models.IntegerField()),
                ('entregas_tardias', models.IntegerField()),
                ('tiempo_promedio_min', models.FloatField(null=True)),
                ('calificacion_promedio', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'vista_rendimiento_repartidor',
                'managed': False,
            },
        ),
    ]
