# Generated by Django 5.0.6 on 2026-07-17 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciontiemporeal',
            name='repartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ubicaciontiemporeal',
            index=models.Index(fields=['repartidor', '-timestamp'], name='idx_ubic_repartidor_tiempo'),
        ),
    ]
